### ISSUE TITLE
update docker hub image

### ISSUE THREAD

**Issue by jitakirin** [romcheck/docker-ungit#2]
Hi, I've seen you merged my PR #1, thanks for that!
However the image hasn't updated on docker hub, maybe the trigger didn't work?  Would you be able to check?
Ta

**Comment by romcheck** [comment]
Indeed, trigger does not work. Somehow, docker hub integration is broken for my account. I will try to repair it later.

I started trigger manually. Looks like image is updated.

**Comment by jitakirin** [comment]
Thanks, that worked.
